### ISSUE TITLE
Поля Откуда и Куда позволяют ввести несколько строк

### ISSUE THREAD

**Issue by mariohuq** [darksasha5/PolyNavi#1]
На экране Главное здание в поля Откуда и Куда можно ввести несколько строк.

Ожидаемое поведение:
Можно ввести только одну строку; вместо Enter доступен Tab (правая нижняя кнопка клавиатуры).

Скрин: 

![Screenshot_2019-08-28-17-31-16-784_com starovoitov polynavi](https://user-images.githubusercontent.com/15021607/63866012-3e221880-c9bb-11e9-8dd3-bd9a96bf91c2.png)

**Comment by AleksandrStarovoitov** [comment]
Пофиксил. Спасибо.
